name = "uber-v3"
main = "src/index.js"
compatibility_date = "2026-06-01"
workers_dev = true

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SocketHub"]

[[migrations]]
tag = "v2"
deleted_classes = ["SocketHub"]

[[kv_namespaces]]
binding = "DRIVERS"
id = "a0b3ddaecec4476f983eb28cc3d8a1e5"

[[kv_namespaces]]
binding = "ORDERS"
id = "e58de8ff6bd14e98a4e845300ae740a5"

[[kv_namespaces]]
binding = "QUOTES"
id = "bc0b2cf092cc44a38a5e970d24aad994"