name = "uber-v3"
main = "src/index.js"
compatibility_date = "2026-06-01"
workers_dev = true

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SocketHub"]

[[migrations]]
tag = "v2"
deleted_classes = ["SocketHub"]

[[kv_namespaces]]
binding = "DRIVERS"
id = "a0b3ddaecec4476f983eb28cc3d8a1e5"

[[d1_databases]]
binding = "DB"
database_name = "transfer-servis52-core"
database_id = "c1d490e4-68f0-4f78-8f53-7d10df7c3395"
migrations_dir = "migrations"